### PR TITLE
changed name of package to metacommunity_diversity

### PR DESCRIPTION
**Pull request by nhongphuc**

### CODE REVIEW

**Review by chhotii-alex — APPROVED** [review]
I don't like the new description but will argue with Ramy about it.

**Comment by Elliot-D-Hill** [comment]
Is "diversity" taken on PyPi? diversity seems a lot more elegant/marketable and easier to write than metacommunity_diversity.

e.g. 

pip install diversity
from diversity import Metacommunity

vs

pip install metacommunity_diversity
from metacommunity_diversity import Metacommunity

**Comment by chhotii-alex** [comment]
Yeah, we know, we know; but indeed the name `diversity` is taken on PyPi.

**Comment by chhotii-alex** [comment]
Now we have decided to change the name to `greylock`. Elliot join our Slack to see the discussion (you have to have been there.)

**Comment by Elliot-D-Hill** [comment]
Ah bummer. I haven't checked the slack in a few months, so I'm out of the loop. It looks 

like "diverse" isn't taken. There is also "hillnumbers"

**Pull request merged**
