### PR TITLE
included rho-hat, beta-hat

### PR DESCRIPTION
**Pull request by nhongphuc**
I made slight changes to the files metacommunity.py and components.py, so that the package computes the quantities dubbed rho-hat and beta-hat (defined in our diversity draft).

### CODE REVIEW

**Comment by Elliot-D-Hill** [comment]
We should add the notebooks/ folder to the .gitignore to keep the paper analyses separate from the package code.

**Comment by nhongphuc** [comment]
Hi Elliot, 

The README file links to those Jupyter notebooks (in the Applications section near the bottom). So, if I add the notebooks/ folder to the .gitignore, I think that will break those links ? So maybe it's best not to add /notebooks to the .gitignore ?

**Comment by Elliot-D-Hill** [comment]
Yes, but it looks like the notebooks and data add about 4 million lines to the repo, so to keep the package code uncluttered I would suggest moving the notebooks and data to a separate GitHub repo (or Gist) exclusively for the paper's code. That way you can still link to them in the README.

**Comment by nhongphuc** [comment]
Okay, sounds good. I'll do that soon.

**Review by chhotii-alex — APPROVED** [review]
Looks good

**Pull request merged**
